# Generated by Django 4.1.4 on 2022-12-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(related_name='my_contacts', to='users.account'),
        ),
    ]
