# Generated by Django 4.1.4 on 2022-12-26 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0002_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomusers',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roomusers',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
