# Generated by Django 4.1.4 on 2022-12-26 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0003_alter_roomusers_user1_alter_roomusers_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomusers',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
